landing/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from ollascomunes import settings
from landing import views
from django.urls import path

app_name = 'landing'
urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('ayudar/', views.ayudar, name='ayudar'),
    path('registrar-vecindad/', views.registrar_vecindad, name='registrar'),
    path('faqs/', views.faqs, name='faqs'),
    path('terminos/', views.terminos, name='terminos'),

]

ollascomunes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from landing import views
from django.contrib.admin.sites import AdminSite


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AdminSite.site_header = 'Administrador de Ollas Comunes'
AdminSite.site_title = 'Ollas Comunes Admin'
AdminSite.index_title = 'Administrador de Ollas Comunes'

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<title>Registrar Localidad</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="{% static 'image/olla-icon.png' %}" type="image/png">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'contact/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'contact/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>


	<div class="container-contact100">
		<div class="contact100-map" id="google_map" data-map-x="40.722047" data-map-y="-73.986422" data-pin="{% static 'contact/images/icons/map-marker.png' %}" data-scrollwhell="0" data-draggable="1"></div>

		<div class="wrap-contact100">
			<form class="contact100-form validate-form" action="{% url 'landing:registrar' %}"  method="POST">
				{% csrf_token %}
				<span class="contact100-form-title">
					Registra tu localidad aquí =)
				</span>
				<p>Llene los datos completos del Representante de la localidad</p>
				<div class="wrap-input100 validate-input" data-validate="Su nombre es requerido">
					<input class="input100" type="text" name="name" placeholder="Nombre Completo">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Se requiere un email válido: ejemplo@ejemplo.com">
					<input class="input100" type="text" name="email" placeholder="Su Correo Electrónico">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate = "La Ciudad o Distrito es importante">
					<input class="input100" type="text" name="city" placeholder="Distrito o Ciudad">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate = "Sin el celular, no podremos comunicarnos fluidamente">
					<input class="input100" type="text" name="phone" placeholder="Celular de contacto">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "La dirección de la localidad es importante">
					<textarea class="input100" name="adress" placeholder="Dirección de la localidad"></textarea>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate = "Este mensaje nos ayuda a conocer un poco más su necesidad">
					<textarea class="input100" name="message" placeholder="Mensaje"></textarea>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn" type="submit">
						Enviar email
					</button>
				</div>
			</form>
		</div>
	</div>



	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'contact/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'contact/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'contact/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'contact/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'contact/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'contact/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'contact/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'contact/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAKFWBqlKAGCeS1rMVoaNlwyayu0e0YRes"></script>
	<script src="{% static 'contact/js/map-custom.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'contact/js/main.js' %}"></script>
</body>
</html>